# <a id='toc1_'></a>[Libreria NUMPY - Paso a Paso](#toc0_)

<img src="./img/logoNumpy.png">

NumPy es la biblioteca central para el cálculo científico en Python. El objeto central de la librería NumPy es el **array NumPy**.    
El array NumPy es un objeto multidimensional de alto rendimiento, diseñado específicamente para realizar operaciones matemáticas, álgebra lineal y cálculos de probabilidad.    

Usar un array NumPy es normalmente mucho más rápido y necesita menos código que usar una lista Python.    
Una gran parte de la biblioteca NumPy esta desarrollada en código C. Esta es una de las razones por las que NumPy es tan rápido.

**Tabla de contenidos**<a id='toc0_'></a>    
- [Libreria NUMPY - Paso a Paso](#toc1_)    
    - [- Centrado en los "ARRAYS"](#toc1_1_1_)    
    - [- Métodos básicos](#toc1_1_2_)    
    - [- Array vs. List](#toc1_1_3_)    
    - [- Producto escalar (Dot Product)](#toc1_1_4_)    
    - [- Comparativa velocidad entre array y list](#toc1_1_5_)    
    - [- Arrays multidimensionales](#toc1_1_6_)    
    - [- Indexado y 'Slicing'](#toc1_1_7_)    
    - [- Indexado booleano](#toc1_1_8_)    
    - [- "Reshaping" - Cambiando el tamaño y la forma a nuestra array](#toc1_1_9_)    
    - [- Concatenación y división de arrays](#toc1_1_10_)    
    - [- Broadcasting](#toc1_1_11_)    
    - [- Funciones y su aplicación sobre los ejes](#toc1_1_12_)    
    - [- Tipos de datos](#toc1_1_13_)    
    - [- Copiar](#toc1_1_14_)    
    - [- Generación de matrices "especiales"](#toc1_1_15_)    
    - [- Numeros aleatorios](#toc1_1_16_)    
    - [- Algebra Lineal (Autovalores (Valores propios o Eigenvalues) / Sistemas lineales)](#toc1_1_17_)    
    - [- Carga de ficheros con Numpy](#toc1_1_18_)    
    - [- EJERCICIOS PROPUESTOS](#toc1_1_19_)

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
import numpy as np

In [2]:
np.__version__

'2.0.2'

### <a id='toc1_1_1_'></a>[- Centrado en los "ARRAYS"](#toc0_)

In [3]:
a = np.array([1,2,3,4,5])
print(a) # [1 2 3 4 5]
print(a.shape) # "forma" del array: (5,)
print(a.dtype) # tipo de dato de los elementos: int32
print(a.ndim) # número de dimensiones: 1
print(a.size) # tamaño - número de elementos: 5
print(a.itemsize) # tamaño - en bytes de cada elemento del array: 8
print(a.nbytes) # tamaño - en bytes del array: 8 bytes * 5 elementos = 40 bytes

[1 2 3 4 5]
(5,)
int64
1
5
8
40


In [4]:
a = np.array([2,71,0,19])
print(a)
print(a.argmax())    # índice del valor más alto
print(a.argmin())    # índice del valor más bajo
print(a.nonzero())   # retorna los índices de los elementos distintos a 0

[ 2 71  0 19]
1
2
(array([0, 1, 3]),)


In [5]:
# ordenar un array
a = np.array([10,2,9,17])
a.sort()
print(a)

[ 2  9 10 17]


### <a id='toc1_1_2_'></a>[- Métodos básicos](#toc0_)

In [6]:
a = np.array([1,2,3])

# acceso y cambio de elementos
print(a[0]) # 1
a[0] = 5
print(a) # [5 2 3]

# operaciones matemáticas elemento a elemento
b = a * np.array([2,0,2])
print(b) # [10  0  6]

print(a.sum()) # 10

1
[5 2 3]
[10  0  6]
10


### <a id='toc1_1_3_'></a>[- Array vs. List](#toc0_)

In [7]:
l = [1,2,3]
a = np.array([1,2,3]) # crear array partiendo de una lista
print(l) # [1, 2, 3]
print(a) # [1 2 3]

# añadir nuevos elementos
l.append(4)
#a.append(4) error: el tamaño de un array es fijo

# se puede añadir elementos pero, básicamente, lo que hacemos es crear nuevos arrays
l2 = l + [5]
print(l2) # [1, 2, 3, 4, 5]

a2 = a + np.array([4])
print(a2) # esto se conoce como "broadcasting". Suma 4 a cada elemento
# -> [5 6 7]

# suma vectorial (esto es técnicamente más correcto que el broadcasting)
a3 = a + np.array([4,4,4])
print(a3) # [5 6 7]

#a3 = a + np.array([4,5]) # error, no se pueden sumar vectores de tamaños distintos

# multiplicación
l2 = 2 * l # list l repetida 2 veces, similar a ejecutar l+l
print(l2) 
# -> [1, 2, 3, 4, 1, 2, 3, 4]

a3 = 2 * a # multiplicación por cada elemento
print(a3) 
# -> [2 4 6]

# modificar cada elemento de la lista
l2 = []
for i in l:
    l2.append(i**2)
print(l2) # [1, 4, 9, 16]

# o usar 'list comprehension'
l2 = [i**2 for i in l]
print(l2) # [1, 4, 9, 16]

a2 = a**2 # -> eleva al cuadrado cada elemento
print(a2) # [1 4 9]

# Nota: una función aplicada a una matriz suele operar elemento a elemento.
a2 = np.sqrt(a) # np.exp(a), np.tanh(a)
print(a2) # [1. 1.41421356 1.73205081]
a2 = np.log(a)
print(a2) # [0. 0.69314718 1.09861229]

[1, 2, 3]
[1 2 3]
[1, 2, 3, 4, 5]
[5 6 7]
[5 6 7]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6]
[1, 4, 9, 16]
[1, 4, 9, 16]
[1 4 9]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


### <a id='toc1_1_4_'></a>[- Producto escalar (Dot Product)](#toc0_)

In [8]:
a = np.array([1,2])
b = np.array([3,4])

# suma de los productos de las entradas correspondientes 
# multiplicar cada uno de los elementos correspondientes y luego tomar la suma

# Modo complejo de realizar para listas
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
print(dot) # 11

# Modo fácil (con NumPy):)
dot = np.dot(a,b)
print(dot) # 11

# paso a paso, manualmente
c = a * b
print(c) # [3 8]
d = np.sum(c)
print(d) # 11


dot = a.dot(b)
print(dot) # 11
dot = (a*b).sum()
print(dot) # 11

# en nuevas versiones
dot = a @ b
print(dot) # 11

11
11
[3 8]
11
11
11
11


### <a id='toc1_1_5_'></a>[- Comparativa velocidad entre array y list](#toc0_)

In [9]:
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a,b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end-start

print('Tiempo con lista:', t1) 
print('Tiempo con array:', t2) 
print('Ratio', t1/t2)         # -> x veces más veloz

Tiempo con lista: 0.2948368030001802
Tiempo con array: 0.001044512000589748
Ratio 282.2722982921314


### <a id='toc1_1_6_'></a>[- Arrays multidimensionales](#toc0_)

In [10]:

# Existe una clase 'matrix' pero no es recomendable usarla
a = np.array([[1,2], [3,4]])
print(a)
# [[1 2]
#  [3 4]]

print(a.shape) # (2, 2)

# Acceso a elementos
# Primero filas y luego columnas.
print(a[0]) # [1 2]
print(a[0][0]) # 1
# o
print(a[0,0]) # 1

# slicing
print(a[:,0]) # todas las filas de la columna 0: [1 3]
print(a[0,:]) # todas las columnas de la fila 0: [1 2]

# matriz traspuesta
a.T

# matriz multiplicación
b = np.array([[3, 4], [5,6]])
c = a.dot(b)

d = a * b # multiplicación elemento a elemento

# las dimensiones internas deben ser idénticas.
b = np.array([[1,2,3], [4,5,6]])
# c = a.dot(b.T) genera error

# determinante
c = np.linalg.det(a)

# inversa
c = np.linalg.inv(a)

# diagonal
c = np.diag(a)
print(c) # [1 4]

# diagonal en un vector devuelve la matriz diagonal (sobrecarga función)
c = np.diag([1,4])
print(c)
# [[1 0]
#  [0 4]]

[[1 2]
 [3 4]]
(2, 2)
[1 2]
1
1
[1 3]
[1 2]
[1 4]
[[1 0]
 [0 4]]


### <a id='toc1_1_7_'></a>[- Indexado y 'Slicing'](#toc0_)

Slicing: De forma similar a las listas de Python, con los arrays de numpy se pueden realizar Slicing.
Dado que los arrays pueden ser multidimensionales, debes especificar una rebanada para cada 
dimensión del array:

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Indexación array de enteros
b = a[0,1]
print(b) # 2

# Slicing (Rebanado)
row0 = a[0,:]
print(row0) # [1 2 3 4]

col0 = a[:, 0]
print(col0) # [1 5 9]

slice_a = a[0:2,1:3]
print(slice_a)
# [[2 3]
#  [6 7]]

# Arrancando slicing desde el final: -1, -2 etc...
last = a[-1,-1]
print(last) # 12

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[1 2 3 4]
[1 5 9]
[[2 3]
 [6 7]]
12


### <a id='toc1_1_8_'></a>[- Indexado booleano](#toc0_)

In [12]:
# Indexación booleana:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# [[1 2]
#  [3 4]
#  [5 6]]

# mismo tamaño con True o False para la condición
bool_idx = a > 2
print(bool_idx)
#  [[False False]
#   [ True  True]
#   [ True  True]]

# nota: esta es una matriz de rango 1!
print(a[bool_idx]) # [3 4 5 6]

#  Podemos hacer todo lo anterior en una sola sentencia:
print(a[a > 2]) # [3 4 5 6]

# np.where(): mismo tamaño con valores modificados
b = np.where(a>2, a, -1)
print(b)
# [[-1 -1]
#  [ 3  4]
#  [ 5  6]]

# fancy indexing: access multiple indices at once
# indexación "vitaminada": acceso a varios índices a la vez
a = np.array([10,19,30,41,50,61])

b = a[[1,3,5]]
print(b) # [19 41 61]

# considera los índices en los que la condición es True
even = np.argwhere(a%2==0).flatten()
print(even) # [0 2 4]

a_even = a[even]
print(a_even) # [10 30 50]

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[-1 -1]
 [ 3  4]
 [ 5  6]]
[19 41 61]
[0 2 4]
[10 30 50]


### <a id='toc1_1_9_'></a>[- "Reshaping" - Cambiando el tamaño y la forma a nuestra array](#toc0_)

In [13]:
a = np.arange(1, 7)
print(a) # [1 2 3 4 5 6]

b = a.reshape((2, 3)) # error si la forma 'no encaja'
print(b)
# [[1 2 3]
#  [4 5 6]]

c = a.reshape((3, 2)) # 3 filas, 2 columnas
print(c)
# [[1 2]
#  [3 4]
#  [5 6]]

# 'newaxis' se usa para crear un nuevo eje en los datos
# necesario cuando el modelo requiere que los datos se reconfiguren de determinada forma
print(a.shape) # (6,)

d = a[np.newaxis, :]
print(d) # [[1 2 3 4 5 6]]
print(d.shape) # (1, 6)

e = a[:, np.newaxis]
print(e)
# [[1]
#  [2]
#  [3]
#  [4]
#  [5]
#  [6]]
print(e.shape) # (6, 1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


### <a id='toc1_1_10_'></a>[- Concatenación y división de arrays](#toc0_)

In [14]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

# combinado en 1d
c = np.concatenate((a, b), axis=None)
print(c) # [1 2 3 4 5 6]

# añadir nueva fila
d = np.concatenate((a, b), axis=0)
print(d)
# [[1 2]
#  [3 4]
#  [5 6]]

# añadir nueva columna: se debe trasponer b!!
e = np.concatenate((a, b.T), axis=1)
print(e)
# [[1 2 5]
#  [3 4 6]]

# hstack: Apilar matrices en secuencia horizontalmente (por columnas). necesita una tupla
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c) # [1 2 3 4 5 6 7 8]

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.hstack((a,b))
print(c)
# [[1 2 5 6]
#  [3 4 7 8]]

# vstack: Apilar matrices en secuencia verticalmente (por filas). necesita una tupla
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)
# [[1 2 3 4]
#  [5 6 7 8]]

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.vstack((a,b))
print(c)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array,2)) # divide array en 2 partes iguales
print(np.array_split(array,3)) # divide array en 3 partes "iguales"

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [16]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array,[3], axis = 0)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [17]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0))  # divide array por la fila 1 y 2

print(np.array_split(array, [1, 3], axis = 1))  # divide array por la columna 1 y 2
# # axis = n_dimensions - 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

### <a id='toc1_1_11_'></a>[- Broadcasting](#toc0_)

Es un poderoso mecanismo que permite a numpy trabajar con arrays de diferentes formas al realizar operaciones aritméticas. Frecuentemente tenemos un array más pequeño y un array más grande, y queremos usar el array más pequeño varias veces para realizar alguna operación en el array más grande.

In [18]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])
z = x + y  # Sumamos v a cada fila de x mediante Broadcasting
print(z) 
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### <a id='toc1_1_12_'></a>[- Funciones y su aplicación sobre los ejes](#toc0_)

In [2]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])

print(a.sum())          # Por defecto (sin especificar)-> 210
print(a.sum(axis=None)) # Suma global -> 210

print(a.sum(axis=0)) # a través de filas --> 1 suma por cada columna 
# -> [24 26 28 30 32 34 36]

print(a.sum(axis=1)) # a través de columnas --> 1 suma por cada fila
# -> [ 70 140]


print(a.mean())          # Por defecto (sin especificar)-> 15.0
print(a.mean(axis=None)) # media total -> 15.0

print(a.mean(axis=0)) # a través de filas -> 1 media por cada columna
# -> [12. 13. 14. 15. 16. 17. 18.]

print(a.mean(axis=1)) # a través de columnas -> 1 media por cada fila
# -> [10. 20.]

# más opciones estadísticas: std, var, min, max

210
210
[24 26 28 30 32 34 36]
[ 70 140]
15.0
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


### <a id='toc1_1_13_'></a>[- Tipos de datos](#toc0_)

In [20]:
# Dejando que Numpy elija el tipo
x = np.array([1, 2])
print(x.dtype) # int32

# Dejando que Numpy elija el tipo
x = np.array([1.0, 2.0])
print(x.dtype) # float64

# Forzando un tipo, especificando la cantidad de bits (precisión)
x = np.array([1, 2], dtype=np.int64) # 8 bytes
print(x.dtype) # int64

x = np.array([1, 2], dtype=np.float32) # 4 bytes
print(x.dtype) # float32

int64
float64
int64
float32


### <a id='toc1_1_14_'></a>[- Copiar](#toc0_)

In [6]:
a = np.array([1,2,3])
print(a)
b = a # only copies reference!
b[0] = 42
print(a) # [42 2 3]

a = np.array([1,2,3])
b = a.copy() # actual copy!
b[0] = 42
print(a) # [1 2 3]
print(b) # [42 2 3]

[1 2 3]
[42  2  3]
[1 2 3]
[42  2  3]


### <a id='toc1_1_15_'></a>[- Generación de matrices "especiales"](#toc0_)

In [22]:
# ceros
a = np.zeros((2,3)) # tamaño en tupla
# [[0. 0. 0.]
#  [0. 0. 0.]]

# unos
b = np.ones((2,3))
# [[1. 1. 1.]
#  [1. 1. 1.]]

# valores concretos
c = np.full((3,3),5.0)
# [[5. 5. 5.]
#  [5. 5. 5.]
#  [5. 5. 5.]]

# identidad
d = np.eye(3) #3x3
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# arange (intervalo)
e = np.arange(10)
# [0 1 2 3 4 5 6 7 8 9]

# linspace (separacion proporcional de valores)
f = np.linspace(0, 10, 5)
# [ 0.  2.5  5.  7.5  10. ]

### <a id='toc1_1_16_'></a>[- Numeros aleatorios](#toc0_)

In [23]:
a = np.random.random((3,2)) # distribución uniforme entre 0 y 1
# [[0.06121857 0.10180167]
#  [0.83321726 0.54906613]
#  [0.94170273 0.19447411]]

b = np.random.randn(3,2) # distribución normal/Gaussiana, media 0 and varianza unitaria 
# cada dimensión es un argumento!!
# [[ 0.56759123 -0.65068333]
#  [ 0.83445762 -0.36436185]
#  [ 1.27150812 -0.32906051]]

c = np.random.randn(10000)
print(c.mean(), c.var(), c.std())
# -0.0014 0.9933 0.9966

d = np.random.randn(10, 3)
print(d.mean()) # media global de todo el array: -0.1076827228882305

# entero aleatorio, menor, mayor, tamaño. El mayor es exclusivo(no forma parte de la elección)
e = np.random.randint(3,10,size=(3,3)) # si solo se pasa un parámetro, entonces desde 0-x
print(e)
# [[6 8 4]
#  [3 6 3]
#  [4 7 8]]

# con entero entre 0 hasta entero exclusivo(no forma parte de la elección)
f = np.random.choice(7, size=10)
# [2 0 4 5 1 3 4 0 0 6]

# con un array, construyendo valores aleatorios desde ese array
g = np.random.choice([1,2,3,4], size=8)
# [4 2 1 3 4 1 4 1]

0.011301786552540398 0.9960657841042557 0.9980309534800289
-0.04386432557538307
[[5 5 9]
 [4 5 4]
 [4 4 8]]


### <a id='toc1_1_17_'></a>[- Algebra Lineal (Autovalores (Valores propios o Eigenvalues) / Sistemas lineales)](#toc0_)

Al hablar de vectores decimos que si tenemos un vector muy grande, con muchos componentes, existen unos algoritmos que nos permiten reducir la dimensionalidad, pero manteniendo cierta cantidad de información.

Entre estos algoritmos se encuentra el PCA o "principal components analysis". Este algoritmo nos permite reducir la dimensionalidad de los vectores, manteniendo cierta cantidad de información.

Internamente, este algoritmo usa autovalores y autovectores en ML para calcular. Lo que se intenta hacer aquí es maximizar la varianza cuando proyectamos los datos en nuevos componentes.

Más información sobre Autovalores y Autovectores: https://www.datacamp.com/es/tutorial/eigenvectors-eigenvalues


In [24]:
# AUTOVALORES
print("AUTOVALORES")
a = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues) # [5. -0.]

# AUTOVECTORES
print("AUTOVECTORES")
print(eigenvectors)

print(eigenvectors[:,0]) # primer autovector
print(eigenvectors[:,1]) # segundo autovector

# VERIFICACION E-VECTOR * E-VALUE = A * E-VECTOR
print("VERIFICACION E-VECTOR * E-VALUE = A * E-VECTOR")
d=eigenvectors[:,0] * eigenvalues[0]
e=a @ eigenvectors[:,0] # @ es el operador de multiplicación de matrices
print(d,e)
print()
# Parecen iguales, pero no lo son debido a la precisión de los cálculos en coma flotante
print("Comparación")
print(d," == ",e) # [2.23606798 6.70820393] == [2.23606798 6.70820393]
print(d==e) # [False False]

# Comparación con tolerancia
print("Comparación con tolerancia")
print(np.allclose(d,e)) # True


AUTOVALORES
[-0.37228132  5.37228132]
AUTOVECTORES
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[-0.82456484  0.56576746]
[-0.41597356 -0.90937671]
VERIFICACION E-VECTOR * E-VALUE = A * E-VECTOR
[ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]

Comparación
[ 0.30697009 -0.21062466]  ==  [ 0.30697009 -0.21062466]
[ True False]
Comparación con tolerancia
True


In [25]:
# SOLUCIÓN DE SISTEMAS DE ECUACIONES LINEALES
#     x1 + x2   = 2200
# 1.5 x1 + 4 x2 = 5050
# -> 2 ecuaciones y 2 incógnitas -> solución única
A = np.array([[1, 1], [1.5, 4]]) # matriz de coeficientes
b = np.array([2200,5050]) # vector de términos independientes

# Ax = b <=> x = A-1 b

# La inversa es lenta y menos precisa
x = np.linalg.inv(A).dot(b) # no recomendado
print(x) # [1500.  700.]

# uso de 'solve' en lugar de 'inv'
x = np.linalg.solve(A,b) # good
print(x) # [1500.  700.]

[1500.  700.]
[1500.  700.]


### <a id='toc1_1_18_'></a>[- Carga de ficheros con Numpy](#toc0_)

Sintaxis: numpy.loadtxt('fname', delimiter=",", encoding=None, dtype=np.float32)


Parámetros:


- fname: El nombre del archivo desde el cual cargar datos.
- delimiter (delimitador) (opcional): delimitador a tener en cuenta al crear una matriz de valores a partir de texto, el valor predeterminado es el espacio en blanco.
- encoding (codificación) (opcional): codificación utilizada para decodificar el archivo de entrada.
- dtype (opcional): tipo de datos de la matriz resultante

Sintaxis: numpy.genfromtxt('fname',delimiter=",",missing_values=None, dtype=np.float32)


Parámetros:


- fname: El archivo desde el que se leerá
- delimiter (delimitador) (opcional): delimitador a tener en cuenta al crear una matriz de valores a partir del texto, el valor predeterminado es cualquier espacio en blanco consecutivo que actúe como delimitador.
- missing_values ​​(opcional): el conjunto de cadenas que se utilizarán en caso de que falte un valor.
- dtype (opcional): tipo de datos de la matriz resultante

In [26]:
# 1) Carga de ficheros con np.loadtxt()
# skiprows=1, ...
data = np.loadtxt('/workspaces/DATASCIENCE/CEIABD_MODULOS_IA/PROGRAMACION DE INTELIGENCIA ARTIFICIAL/NOTEBOOKS DEL AULA/datasets/testFile.csv', delimiter=",",dtype=np.float32)
print(data.shape, data.dtype)

# 2) Carga de ficheros con np.genfromtxt()
# similar pero con más parámetros de configuración
# skip_header=0, missing_values="---", filling_values=0.0, ...
data = np.genfromtxt('/workspaces/DATASCIENCE/CEIABD_MODULOS_IA/PROGRAMACION DE INTELIGENCIA ARTIFICIAL/NOTEBOOKS DEL AULA/datasets/testFile.csv', delimiter=",", dtype=np.float32)
print(data.shape)

(3, 3) float32
(3, 3)


### <a id='toc1_1_19_'></a>[EJERCICIOS PROPUESTOS](#toc0_)
- Ejercicios para practicar NumPy: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb
- Con pistas: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints.md
- Soluciones en: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md

- __No mires las soluciones desde el principio__. Intenta resolverlos por tu cuenta

## <img src="img/by-nc.png" width="200">