# Gestión de datos en Pytorch: Datasets y Dataloaders

El módulo **torch.utils.data** de PyTorh tiene clases muy útiles para la carga de datos necesaria en los procesos de entrenamiento y validación.   
En este notebook vamos a ver dos de las clases más importantes: *torch.utils.data.Dataset* para albergar los datos y *torch.utils.data.DataLoader* para cargar los datos.

Las clases **Dataset** permiten instanciar objetos con el conjunto de datos que se van a cargar. PyTorch permite crear dos tipos distintos de datasets:  
- Map-style: Implementa los métodos **getitem()** and **len()** y representa un mapeo de claves/índices a valores del conjunto de datos. La clase Dataset sería un ejemplo y es el tipo de dataset que veremos.
- Iterable-style: Implementa el método **iter()** y representa un iterable sobre los datos. La clase IterableDataset es un ejemplo.   

A continuación vamos a ver un ejemplo de definición de una clase que contiene un conjunto de datos. Esta clase hereda la clase Dataset y sobreescribe el método getitem() que permite obtener una muestra de los datos a partir de la clave/índice y el método len() que devuelve el tamaño de los datos. A modo de ejemplo creamos unos datos con una lista de 1000 valores como muestra y y otra lista de 1000 valores como etiquetas.


In [1]:
import torch
from torch.utils.data import Dataset

class NumbersDataset(Dataset):
    def __init__(self):
        self.samples = list(range(1, 1001))
        self.labels = list(range(1000, 2001))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx], self.labels[idx]

Creamos una instancia de la clase que hemos definido. Vemos el tamaño de los datos y varias muestras de los datos.

In [2]:
dataset = NumbersDataset()
print(len(dataset))
print(dataset[100])
print(dataset[122:125])

1000
(101, 1100)
([123, 124, 125], [1122, 1123, 1124])


La clase **torch.utils.data.DataLoader** es la clase principal para cargar los datos. A esta clase se le pasa como argumento un objeto Dataset (map-style o iterable style) y tiene varias opciones como:

- Definir el orden y la forma de cargar los datos.
- Batching automático: Se carga un batch de datos de manera automática o manual.
- Realizar la carga de datos en un proceso o en múltiples procesos.
- Ubicar los tensores en memoria page-locked para agilizar su transferencia a la GPU.  

A continuación, creamos una instancia de la clase torch.utils.data.DataLoader a la que pasamos el objeto dataset que hemos creado. Definimos un tamaño de batch de 10 y shuffle=False para que no se cambie el orden de los datos en cada epoch (recorrido completo de los datos).

In [3]:
batch_size=10

train_loader = torch.utils.data.DataLoader(dataset=dataset, batch_size=batch_size, shuffle=False)
for i, (numbers, labels) in enumerate(train_loader):
  if  i<11:
    print('Batch number %d'%(i+1))
    print(numbers, labels)

Batch number 1
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) tensor([1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])
Batch number 2
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]) tensor([1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019])
Batch number 3
tensor([21, 22, 23, 24, 25, 26, 27, 28, 29, 30]) tensor([1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029])
Batch number 4
tensor([31, 32, 33, 34, 35, 36, 37, 38, 39, 40]) tensor([1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039])
Batch number 5
tensor([41, 42, 43, 44, 45, 46, 47, 48, 49, 50]) tensor([1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049])
Batch number 6
tensor([51, 52, 53, 54, 55, 56, 57, 58, 59, 60]) tensor([1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059])
Batch number 7
tensor([61, 62, 63, 64, 65, 66, 67, 68, 69, 70]) tensor([1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069])
Batch number 8
tensor([71, 72, 73, 74, 75, 76, 77, 78, 79, 80]) tenso

Ahora, creamos otra instancia pero con *shuffle=True* para que se cambie el orden de los datos en cada epoch.

In [4]:
train_loader = torch.utils.data.DataLoader(dataset=dataset, batch_size=batch_size, shuffle=True)
for i, (numbers, labels) in enumerate(train_loader):
  if  i<11:
    print('Batch number %d'%(i+1))
    print(numbers, labels)

Batch number 1
tensor([248, 661, 179, 766, 235, 299, 935, 475, 969, 765]) tensor([1247, 1660, 1178, 1765, 1234, 1298, 1934, 1474, 1968, 1764])
Batch number 2
tensor([737, 976, 124,  83, 514, 569,  13, 324, 271, 477]) tensor([1736, 1975, 1123, 1082, 1513, 1568, 1012, 1323, 1270, 1476])
Batch number 3
tensor([351, 480, 507, 520, 236, 690, 358, 984, 944, 553]) tensor([1350, 1479, 1506, 1519, 1235, 1689, 1357, 1983, 1943, 1552])
Batch number 4
tensor([ 59,  60, 319, 608,  37, 863, 602, 311, 132, 571]) tensor([1058, 1059, 1318, 1607, 1036, 1862, 1601, 1310, 1131, 1570])
Batch number 5
tensor([442, 995, 655,  51,  55, 270, 788, 651, 688, 425]) tensor([1441, 1994, 1654, 1050, 1054, 1269, 1787, 1650, 1687, 1424])
Batch number 6
tensor([371, 967, 119, 422, 141, 915, 394, 599, 201, 452]) tensor([1370, 1966, 1118, 1421, 1140, 1914, 1393, 1598, 1200, 1451])
Batch number 7
tensor([635,  96, 199, 112, 467, 326, 206, 728, 738, 666]) tensor([1634, 1095, 1198, 1111, 1466, 1325, 1205, 1727, 1737, 1665])